# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ğŸš€ Check project in different node versions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  check-node-build:
    name: ğŸ§© Build, test and validate code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
    - name: ğŸ”€ Checkout code from repository
      uses: actions/checkout@v4
    - name: ğŸ› ï¸ Setup node version ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: ğŸ“¦ Install dependencies
      run: npm install
    - name: ğŸ—ï¸ Build project
      run: npm run build --if-present
    - name: ğŸ§ª Run tests
      run: npm test --if-present
    - name: ğŸ” Validate commits to use the commitlint syntax
      run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
